### ISSUE TITLE
Errors when running test-app

### ISSUE THREAD

**Issue by dmitriz** [andywer/webpack-blocks#64]
```bash
> @ start /Users/dmitrizaitsev/Repos/webpack-blocks/test-app
> NODE_ENV=development webpack-dev-server --config webpack.config.babel.js

/Users/dmitrizaitsev/Repos/webpack-blocks/test-app/node_modules/@webpack-blocks/babel6/index.js:22
          test: fileTypes('application/javascript'),
                ^

TypeError: fileTypes is not a function
    at /Users/dmitrizaitsev/Repos/webpack-blocks/test-app/node_modules/@webpack-blocks/babel6/index.js:22:17
    at /Users/dmitrizaitsev/Repos/webpack-blocks/test-app/node_modules/@webpack-blocks/core/src/index.js:94:29
    at Array.reduce (native)
    at invokeConfigSetters (/Users/dmitrizaitsev/Repos/webpack-blocks/test-app/node_modules/@webpack-blocks/core/src/index.js:92:24)
    at Object.createConfig (/Users/dmitrizaitsev/Repos/webpack-blocks/test-app/node_modules/@webpack-blocks/core/src/index.js:33:18)
    at createConfig (/Users/dmitrizaitsev/Repos/webpack-blocks/test-app/node_modules/@webpack-blocks/webpack2/index.js:41:15)
    at Object.<anonymous> (/Users/dmitrizaitsev/Repos/webpack-blocks/test-app/webpack.config.babel.js:11:18)
    at Module._compile (module.js:570:32)
    at loader (/Users/dmitrizaitsev/Repos/webpack-blocks/test-app/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/dmitrizaitsev/Repos/webpack-blocks/test-app/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at requireConfig (/Users/dmitrizaitsev/Repos/webpack-blocks/test-app/node_modules/webpack/bin/convert-argv.js:97:18)

npm ERR! Darwin 12.6.0
npm ERR! argv "/usr/local/bin/node" "/Users/dmitrizaitsev/.npm-global/bin/npm" "start"
npm ERR! node v6.9.2
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! @ start: `NODE_ENV=development webpack-dev-server --config webpack.config.babel.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script 'NODE_ENV=development webpack-dev-server --config webpack.config.babel.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=development webpack-dev-server --config webpack.config.babel.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dmitrizaitsev/Repos/webpack-blocks/test-app/npm-debug.log
```

**Comment by andywer** [comment]
Thanks for reporting, @dmitriz! :)

I think it's because the test-app's `package.json` depedencies have not been completely updated :-/

Please try installing `@webpack-blocks/babel6 0.3.0` and `@webpack-blocks/css-modules 0.3.0` for now. I will fix it!

**Comment by andywer** [comment]
I guess the test-app needs its own tests... Opening a new issue (#16) for that.

**Comment by dmitriz** [comment]
Thanks, that works, awesome! The config is really clean!
